
	# g++ $(enum) -o enums_and_struct.o
	# g++ $(blackjack) -o blackjack.o -g -Wall -Wextra

QMAKE_CC=gcc
QMAKE_CXX=g++

enum        = main_ead.cpp enums_and_structs.cpp
blackjack   = kortklasse.cpp kortstokk.cpp blackjack.cpp main_black.cpp

all:
	g++ $(blackjack) -o blackjack.o
