all: main

main: main.cpp cannonball.cpp utilities.cpp
	g++ main.cpp cannonball.cpp utilities.cpp


test: tests.cpp cannonball.cpp utilities.cpp
	g++ tests.cpp cannonball.cpp utilities.cpp -o test


clean:
	rm *.out
